//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFAppNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducationEntities : DbContext
    {
        public EducationEntities()
            : base("name=EducationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendancies> Attendancies { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<StudentPrices> StudentPrices { get; set; }
        public virtual DbSet<Students> Students { get; set; }
    }
}
